version: "3"
services:
  app:
    depends_on:
      - db
      - kafka
      - zookeeper
    image: exlibris:latest
    ports:
      - 8080:8080
    restart: always
    env_file:
      - app.env

  db:
    image: postgres
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      - 5432:5432

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "exlibris:3:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

volumes:
  db-data:


