version: '3.0'
services:
  app:
    depends_on:
      - db
    image: exlibris:latest
    ports:
      - 8080:8080
    env_file:
      - app.env

  db:
    image: postgres
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      - 5432:5432

volumes:
  db-data:

