version: "3"
services:
  db:
    image: postgres
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      - 5432:5432

  app:
    depends_on:
      - api
    environment:
      - VUE_APP_API_ORIGIN=http://localhost:8081/api
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - 8080:8080

  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 8081:8080
    env_file:
        - app.env
    volumes:
      - .:/build/

volumes:
  db-data:


