version: "3"
services:
  db:
    image: postgres
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      - 5432:5432
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8081:8080
    env_file:
        - app.env
    volumes:
      - .:/build/

volumes:
  db-data:


