version: '3.0'
services:
  app:
    depends_on:
      - db
    image: exlibris-fed/exlibris:latest
    ports:
      - 8080:8080
    env_file:
      - app.env

  db:
    image: postgres
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/postgres/data

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30 --debug

volumes:
  db-data:

