name: CI

on: [push]

jobs:
  lint-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        fetch_depth: 1

    - name: Install dependencies
      run: npm i

    - name: Lint
      run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        fetch_depth: 1
    - name: Build
      run: docker build .
