name: Deploy (CI/CD)
on:
  push:
    branches:
      - master

jobs:
  build:
    name: go build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: build
        run: docker build -t exlibrisfed/exlibris:latest

      - name: push to DockerHub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker push exlibrisfed/exlibris:latest
